### ISSUE TITLE
Создать папку с фотографиями Пиба Уна

### ISSUE THREAD

**Issue by ViRGiL175** [ViRGiL175/piba-un-learning#2]
Название обсудим здесь.

**Comment by ladnonevazhno** [comment]
Объясни, в какой форме это делать вообще

**Comment by ViRGiL175** [comment]
Создай папку для фото с каким-нибудь названием. В него заливай несколько фоток Пиба Уна с какими-нибудь названиями. Желательно сразу какой-то удобно названные.

Можно привыкнуть называть ресурсы маленькими буквами, вместо пробелов подчеркивание, плюс можешь называть файлы идентично, чтоб они отличались только на цифру.

**Comment by ladnonevazhno** [comment]
Создам, залью. А потом надо запушить сюда в проект или что?

**Comment by ViRGiL175** [comment]
Конечно. Все как обычно в Гите.

**Comment by ladnonevazhno** [comment]
Называю папку "pibaun_photos", а файлы в ней - "pibaun_photos_N", где N - номер фотографии.
